import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'

const roboto = Inter({
  weight: '500',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'CRUD App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="box ">
          <Navbar />
          <div className="my-8">{children}</div>
        </div>
      </body>
    </html>
  )
}
